from __future__ import annotations

from dataclasses import dataclass
import math


@dataclass(frozen=True)
class RolloutEnvelope:
    payload: object
    policy_version: int
    worker_id: str = "worker"
    episode_id: str = "episode"


class StalenessPolicy:
    """Reject or downweight experience generated by stale policies.

    Experience stamped with a *future* policy version is invalid rather than fresh;
    accepting it can silently hide versioning/order bugs in asynchronous training.
    """

    def __init__(self, max_lag: int = 4, half_life: float = 2.0):
        self.max_lag = int(max_lag)
        self.half_life = float(half_life)
        if self.max_lag < 0:
            raise ValueError("max_lag must be >= 0")
        if not math.isfinite(self.half_life) or self.half_life <= 0:
            raise ValueError("half_life must be finite and > 0")

    def lag(self, current_version, envelope):
        return int(current_version) - int(envelope.policy_version)

    def weight(self, current_version, envelope):
        lag = self.lag(current_version, envelope)
        if lag < 0 or lag > self.max_lag:
            return 0.0
        return float(math.exp(-math.log(2) * lag / self.half_life))

    def accept(self, current_version, envelope):
        return self.weight(current_version, envelope) > 0
